### PR TITLE
§ 4 Medlemmer

### PR DESCRIPTION
**Pull request by Andersos**

### CODE REVIEW

**Review by leftieFriele — COMMENTED** [review]
Adding a paid member membership for WR is something which requires a process to ensure it makes sense.
- are there requirements as to how to document memerbship and how that membership is stored in a registry?
- can anyone become a member? if not, what are the selection criteria?
- what is the benefit of adding memberships?

I think a membership makes sense in case we can provide some value. Memberships like JavaBin / JavaZone makes little sense to me as it is just not adding any value.

**Comment by Andersos** [comment]
We need to have a member system so we can have members to vote in the general assembly (Årsmøte) and "valgbarhet til verv innen foreningen" so we can make a board (styre) that will have the responsibility to plan and arrange the conference.

> are there requirements as to how to document memerbship and how that membership is stored in a registry?

It will be the boards jobb to keep track of who the members are. As long as we keep a spreadsheet with the information that is sufficient. I have added an example here https://docs.google.com/spreadsheets/d/1YJPW3Ri8lpYMIRGdCiZ18_efWLtVmJxONMZJtJCuZyw/edit?usp=sharing.

I have added a line about styre getting the job of keeping track of the members here https://github.com/webrebels/rebeladmin/pull/9/files#diff-de78ae1b0c064280d8738f8f06b1cba2R105 

> can anyone become a member? if not, what are the selection criteria?

We have no selection criteria for becoming a member of the organisation today. If we want to have some criteria adding it to §4 would be appropriate. Personally I dont see what type of criteria that would be but it will be up to the general assembly to accept changes to the statute (vedtekter). If you have suggestions for criteria you are open to make a pull request with suggested changes =)

> what is the benefit of adding memberships?

Today we have no benefit. I suggest adding three benefits of becoming a member:

- valgbarhet til verv innen foreningen
So we can make a board (styre)
- tilgang til alle foreningens arrangementer
If you are a member you can attend arrangements. I dont know if Web Rebels has many of these today but might be in the future.
- redusert pris på konferansen fastsatt av årsmøte
This might be a controversial point. I am open for dropping it but this might be a nice way to recruit new members if we want that.

> Memberships like JavaBin / JavaZone makes little sense to me as it is just not adding any value.

I can understand your thinking here and JavaZone might be a little blod in signing up new members by making every ticketholder to the conference a member. But an organization needs members so there needs to be a way to become a member.

JavaZone has their statutes (vedtekter) here https://wiki.java.no/display/javabin/Vedtekter

**Comment by leftieFriele** [comment]
There are no requirements for an organization of the type Web Rebels are to have members and a registry, at least that has never been mentioned as a requirement. The way we have operated the conference so far is within the regulations which exists for the type of organization we are in Brønnøysun. You can have an organization without the option for anyone to join. That is something you can choose to do in order to get government funding or similar.  Or start having memberships as a way to move away from a sponsorbased way of funding the conference. However if that is the goal we need to have a much better offering in order for people to join.

**Comment by Andersos** [comment]
With no members of the organisation nobody can act on behalf of it. At least the people that organize the conference today needs to be members but preferably they are also part of the board (styret). 

> The way we have operated the conference so far is within the regulations which exists for the type of organization we are in Brønnøysun.

This is not true. 

>  You can have an organization without the option for anyone to join. 

One of the conditions (krav) to have this type of organisation is that it has a board (styret). The board is elected at the general assembly (årsmøte). The details of electing a board is detailed in our statutes (vedtekter). Today we are unfortunately not following our own statues (vedtekter) but hopefully we can change that by having a general assembly (årsmøte) this summer.

> Or start having memberships as a way to move away from a sponsorbased way of funding the conference.

Using any money sponsored or not in the name of the organisation requires someone that is allowed to represent it. Right now with no members and no elected board nobody can do that.

> However if that is the goal we need to have a much better offering in order for people to join.

What type of offering Web Rebelebs has for its members is up the the general assembly, voted on by the members of the organisation. Members are welcome to make suggestions that should be submitted to the general assembly.

**Comment by Andersos** [comment]
This is written in our statutes (vedtekter) @leftieFriele. 

> § 5 Stemmerett og valgbarhet
Alle medlemmer har stemmerett og er valgbare til tillitsverv i foreningen.

So we need members to have people with voting rights and people that can be in the board (styret) to represent the organisation.

**Comment by leftieFriele** [comment]
Yes, but membership does not have to be open to everyone. We've previously said that those organizing are members and from the members the board is elected. Well within the official requirements.
Currently the "daglig leder" and "styreleder" are allowed to sign an behalf of the conference. This can be changed at any time to be things such as anyone in the board. All of this is possible under the current way of running the organization.

**Comment by Andersos** [comment]
> Yes, but membership does not have to be open to everyone.

You are right Web Rebels dose not have to make membership open for everyone. You are open to suggest criteria for this but today there is nothing preventing anyone from becoming a member according to our statutes (vedtekter). If you want to limit the members you could suggest something like "You need to be invited by a member" as a criteria. My personal opinions is that we should be friendly and open to people that want to be part of this but the deciding of how we should change our statutes is the general assembly voted on by the members.

> We've previously said that those organising are members

This is not part of our statutes (vedtekter) so this is not true according to official requirements.

**Review by trygve-lie — APPROVED** [review]

**Pull request merged**
